# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdfd5f2ce0d47ecb5bbd6febfb85c994ad9620b76413753f0c1832e7ff36e7e1a0d6d3dd43f3ae899d100164c8588395effa75e09114835cbe8071df3155a39b

test:
  secret_key_base: 21140712f26cb29c02cfb4bcf236b82dd874180820ca9df053c1058c4b4e40ed05a0a49bc97d4b0abbaaeafceebc37283bed811bda561442e53f29d3da7f3022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
